//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Good> Good { get; set; }
        public virtual DbSet<Good_Type> Good_Type { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_Good> Order_Good { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
