//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int id { get; set; }
        public string second_name { get; set; }
        public string first_name { get; set; }
        public string patronymic { get; set; }
        public string number_phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
